In [1]:
import pandas as pd

In [2]:
training_df = pd.read_csv('training_set_features.csv')
training_df.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0   
1              1          3.0            2.0                        0.0   
2              2          1.0            1.0                        0.0   
3              3          1.0            1.0                        0.0   
4              4          2.0            1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
2                   1.0                   0.0                    0.0   
3                   1.0                   0.0                    1.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
2                          0.0                      0.0   
3                          1.0                      0.0   
4                          1.0                      0.0   

   behavioral_touch_face  ...             income_poverty  marital_status  \
0                    1.0  ...              Below Poverty     Not Married   
1                    1.0  ...              Below Poverty     Not Married   
2                    0.0  ...  <= $75,000, Above Poverty     Not Married   
3                    0.0  ...              Below Poverty     Not Married   
4                    1.0  ...  <= $75,000, Above Poverty         Married   

   rent_or_own   employment_status  hhs_geo_region                census_msa  \
0          Own  Not in Labor Force        oxchjgsf                   Non-MSA   
1         Rent            Employed        bhuqouqj  MSA, Not Principle  City   
2          Own            Employed        qufhixun  MSA, Not Principle  City   
3         Rent  Not in Labor Force        lrircsnp       MSA, Principle City   
4          Own            Employed        qufhixun  MSA, Not Principle  City   

   household_adults  household_children  employment_industry  \
0               0.0                 0.0                  NaN   
1               0.0                 0.0             pxcmvdjn   
2               2.0                 0.0             rucpziij   
3               0.0                 0.0                  NaN   
4               1.0                 0.0             wxleyezf   

   employment_occupation  
0                    NaN  
1               xgwztkwe  
2               xtkaffoo  
3                    NaN  
4               emcorrxb  

[5 rows x 36 columns]

In [3]:
training_df.shape

(26707, 36)

In [4]:
testing_df = pd.read_csv('test_set_features.csv')
testing_df.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0          26707          2.0            2.0                        0.0   
1          26708          1.0            1.0                        0.0   
2          26709          2.0            2.0                        0.0   
3          26710          1.0            1.0                        0.0   
4          26711          3.0            1.0                        1.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   1.0                   0.0                    1.0   
1                   0.0                   0.0                    0.0   
2                   0.0                   1.0                    1.0   
3                   0.0                   0.0                    0.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          1.0                      0.0   
1                          0.0                      0.0   
2                          1.0                      1.0   
3                          0.0                      0.0   
4                          1.0                      1.0   

   behavioral_touch_face  ...             income_poverty  marital_status  \
0                    1.0  ...                  > $75,000     Not Married   
1                    0.0  ...              Below Poverty     Not Married   
2                    1.0  ...                  > $75,000         Married   
3                    0.0  ...  <= $75,000, Above Poverty         Married   
4                    1.0  ...  <= $75,000, Above Poverty     Not Married   

   rent_or_own   employment_status  hhs_geo_region                census_msa  \
0         Rent            Employed        mlyzmhmf  MSA, Not Principle  City   
1         Rent            Employed        bhuqouqj                   Non-MSA   
2          Own            Employed        lrircsnp                   Non-MSA   
3          Own  Not in Labor Force        lrircsnp  MSA, Not Principle  City   
4          Own            Employed        lzgpxyit                   Non-MSA   

   household_adults  household_children  employment_industry  \
0               1.0                 0.0             atmlpfrs   
1               3.0                 0.0             atmlpfrs   
2               1.0                 0.0             nduyfdeo   
3               1.0                 0.0                  NaN   
4               0.0                 1.0             fcxhlnwr   

   employment_occupation  
0               hfxkjkmi  
1               xqwwgdyp  
2               pvmttkik  
3                    NaN  
4               mxkfnird  

[5 rows x 36 columns]

In [5]:
testing_df.shape

(26708, 36)

In [6]:
training_labels = pd.read_csv('training_set_labels.csv')
training_labels.head()

respondent_id  xyz_vaccine  seasonal_vaccine
0              0            0                 0
1              1            0                 1
2              2            0                 0
3              3            0                 1
4              4            0                 0

In [7]:
training_labels.shape

(26707, 3)

### Cleaning training data set

In [8]:
training_df.isnull().sum()

respondent_id                      0
xyz_concern                       92
xyz_knowledge                    116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_xyz_vacc_effective       391
opinion_xyz_risk                 388
opinion_xyz_sick_from_vacc       395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
m

In [9]:
training_df['age_group'].unique()

array(['55 - 64 Years', '35 - 44 Years', '18 - 34 Years', '65+ Years',
       '45 - 54 Years'], dtype=object)

In [10]:
#taking max age as 85 years and replacing with average age
training_df['age_group'].replace({'55 - 64 Years': 60, '35 - 44 Years': 40, '18 - 34 Years': 25, '65+ Years': 75,
       '45 - 54 Years': 50}, inplace=True)
training_df['age_group'].unique()

array([60, 40, 25, 75, 50])

In [11]:
training_df.dtypes

respondent_id                    int64
xyz_concern                    float64
xyz_knowledge                  float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_xyz                float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_xyz_vacc_effective     float64
opinion_xyz_risk               float64
opinion_xyz_sick_from_vacc     float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                        int64
education                       object
race                            object
sex                      

In [12]:
training_df['education'].value_counts()

education
College Graduate    10097
Some College         7043
12 Years             5797
< 12 Years           2363
Name: count, dtype: int64

In [13]:
training_df.fillna({'education': 'College Graduate'}, inplace = True)

In [14]:
training_df['education'].unique()

array(['< 12 Years', '12 Years', 'College Graduate', 'Some College'],
      dtype=object)

In [15]:
training_df['education'] = training_df['education'].astype('category')
training_df['education'] = training_df['education'].cat.codes
training_df['education'].unique()

array([1, 0, 2, 3], dtype=int8)

In [16]:
training_df['race'].value_counts()

race
White                21222
Black                 2118
Hispanic              1755
Other or Multiple     1612
Name: count, dtype: int64

In [17]:
training_df['race'] = training_df['race'].astype('category')
training_df['race'] = training_df['race'].cat.codes
training_df['race'].unique()

array([3, 0, 2, 1], dtype=int8)

In [18]:
training_df['sex'].value_counts()

sex
Female    15858
Male      10849
Name: count, dtype: int64

In [19]:
#replacing male and female with 1,0
training_df['sex'].replace({'Male': 1, 'Female': 0}, inplace=True)
training_df['sex'].unique()

array([0, 1])

In [20]:
training_df['income_poverty'].value_counts()

income_poverty
<= $75,000, Above Poverty    12777
> $75,000                     6810
Below Poverty                 2697
Name: count, dtype: int64

In [21]:
training_df.fillna({'income_poverty': '<= $75,000, Above Poverty'}, inplace = True)

In [22]:
training_df['income_poverty'] = training_df['income_poverty'].astype('category')
training_df['income_poverty'] = training_df['income_poverty'].cat.codes
training_df['income_poverty'].unique()

array([2, 0, 1], dtype=int8)

In [23]:
training_df['marital_status'].value_counts()

marital_status
Married        13555
Not Married    11744
Name: count, dtype: int64

In [24]:
training_df.fillna({'marital_status': 'Married'}, inplace = True)

In [25]:
#replacing Marreid and Not Married with 1,0
training_df['marital_status'].replace({'Married': 1, 'Not Married': 0}, inplace=True)
training_df['marital_status'].value_counts()

marital_status
1    14963
0    11744
Name: count, dtype: int64

In [26]:
training_df['rent_or_own'].value_counts()

rent_or_own
Own     18736
Rent     5929
Name: count, dtype: int64

In [27]:
training_df.fillna({'rent_or_own': 'Own'}, inplace = True)

In [28]:
#replacing Own and Rent with 1,0
training_df['rent_or_own'].replace({'Own': 1, 'Rent': 0}, inplace=True)
training_df['rent_or_own'].unique()

array([1, 0])

In [29]:
training_df['employment_status'].value_counts()

employment_status
Employed              13560
Not in Labor Force    10231
Unemployed             1453
Name: count, dtype: int64

In [30]:
training_df.fillna({'employment_status': 'Employed'}, inplace = True)

In [31]:
#replacing Employed with 1 , Not in labor Force and Unemployed with 0
training_df['employment_status'].replace({'Employed': 1, 'Not in Labor Force' :0 ,'Unemployed': 0}, inplace=True)
training_df['employment_status'].unique()

array([0, 1])

In [32]:
training_df['hhs_geo_region'].value_counts()

hhs_geo_region
lzgpxyit    4297
fpwskwrf    3265
qufhixun    3102
oxchjgsf    2859
kbazzjca    2858
bhuqouqj    2846
mlyzmhmf    2243
lrircsnp    2078
atmpeygn    2033
dqpwygqj    1126
Name: count, dtype: int64

In [33]:
training_df['hhs_geo_region'] = training_df['hhs_geo_region'].astype('category')
training_df['hhs_geo_region'] = training_df['hhs_geo_region'].cat.codes
training_df['hhs_geo_region'].unique()

array([8, 1, 9, 5, 0, 6, 3, 7, 2, 4], dtype=int8)

In [34]:
training_df['census_msa'].value_counts()

census_msa
MSA, Not Principle  City    11645
MSA, Principle City          7864
Non-MSA                      7198
Name: count, dtype: int64

In [35]:
training_df['census_msa'] = training_df['census_msa'].astype('category')
training_df['census_msa'] = training_df['census_msa'].cat.codes
training_df['census_msa'].unique()

array([2, 0, 1], dtype=int8)

In [36]:
training_df['employment_industry'].value_counts()

employment_industry
fcxhlnwr    2468
wxleyezf    1804
ldnlellj    1231
pxcmvdjn    1037
atmlpfrs     926
arjwrbjb     871
xicduogh     851
mfikgejo     614
vjjrobsf     527
rucpziij     523
xqicxuve     511
saaquncn     338
cfqqtusy     325
nduyfdeo     286
mcubkhph     275
wlfvacwt     215
dotnnunm     201
haxffmxo     148
msuufmds     124
phxvnwax      89
qnlwzans      13
Name: count, dtype: int64

In [37]:
training_df['employment_industry'] = training_df['employment_industry'].astype('category')
training_df['employment_industry'] = training_df['employment_industry'].cat.codes
training_df['employment_industry'].unique()

array([-1, 12, 14, 18, 15, 19,  6, 17, 10,  4, 16,  0,  1,  9, 20, 11,  3,
        8,  2,  7,  5, 13], dtype=int8)

In [38]:
import numpy as np

In [39]:
training_df['employment_industry'].replace(-1,np.nan, inplace = True)
training_df['employment_industry'].unique()

array([nan, 12., 14., 18., 15., 19.,  6., 17., 10.,  4., 16.,  0.,  1.,
        9., 20., 11.,  3.,  8.,  2.,  7.,  5., 13.])

In [40]:
training_df['employment_occupation'].value_counts()

employment_occupation
xtkaffoo    1778
mxkfnird    1509
emcorrxb    1270
cmhcxjea    1247
xgwztkwe    1082
hfxkjkmi     766
qxajmpny     548
xqwwgdyp     485
kldqjyjy     469
uqqtjvyb     452
tfqavkke     388
ukymxvdu     372
vlluhbov     354
oijqvulv     344
ccgxvspp     341
bxpfxfdn     331
haliazsg     296
rcertsgn     276
xzmlyyjv     248
dlvbwzss     227
hodpvpew     208
dcjcmpih     148
pvmttkik      98
Name: count, dtype: int64

In [41]:
training_df['employment_occupation'] = training_df['employment_occupation'].astype('category')
training_df['employment_occupation'] = training_df['employment_occupation'].cat.codes
training_df['employment_occupation'].unique()

array([-1, 19, 21,  5, 18, 20,  1, 13,  9, 10,  7,  0, 16,  2,  6,  4, 22,
       11, 14, 15,  8, 17, 12,  3], dtype=int8)

In [42]:
training_df['employment_occupation'].replace(-1,np.nan, inplace = True)
training_df['employment_occupation'].unique()

array([nan, 19., 21.,  5., 18., 20.,  1., 13.,  9., 10.,  7.,  0., 16.,
        2.,  6.,  4., 22., 11., 14., 15.,  8., 17., 12.,  3.])

In [43]:
training_df.dtypes

respondent_id                    int64
xyz_concern                    float64
xyz_knowledge                  float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_xyz                float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_xyz_vacc_effective     float64
opinion_xyz_risk               float64
opinion_xyz_sick_from_vacc     float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                        int64
education                         int8
race                              int8
sex                      

In [44]:
training_df.isnull().sum()

respondent_id                      0
xyz_concern                       92
xyz_knowledge                    116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_xyz_vacc_effective       391
opinion_xyz_risk                 388
opinion_xyz_sick_from_vacc       395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                          0
race                               0
sex                                0
income_poverty                     0
m

In [45]:
replace_mean_columns = ['xyz_concern','xyz_knowledge','behavioral_antiviral_meds','behavioral_avoidance','behavioral_face_mask','behavioral_wash_hands',
                        'behavioral_large_gatherings','behavioral_outside_home','behavioral_touch_face','doctor_recc_xyz',
                        'doctor_recc_seasonal','chronic_med_condition','child_under_6_months','health_worker','opinion_xyz_vacc_effective',
                        'opinion_xyz_risk','opinion_xyz_sick_from_vacc','opinion_seas_vacc_effective','opinion_seas_risk',
                        'opinion_seas_sick_from_vacc','household_adults','household_children']


for col in training_df.columns:
    if col in replace_mean_columns:
        training_df[col].fillna(training_df[col].mean(), inplace=True)

training_df.isnull().sum()

respondent_id                      0
xyz_concern                        0
xyz_knowledge                      0
behavioral_antiviral_meds          0
behavioral_avoidance               0
behavioral_face_mask               0
behavioral_wash_hands              0
behavioral_large_gatherings        0
behavioral_outside_home            0
behavioral_touch_face              0
doctor_recc_xyz                    0
doctor_recc_seasonal               0
chronic_med_condition              0
child_under_6_months               0
health_worker                      0
health_insurance               12274
opinion_xyz_vacc_effective         0
opinion_xyz_risk                   0
opinion_xyz_sick_from_vacc         0
opinion_seas_vacc_effective        0
opinion_seas_risk                  0
opinion_seas_sick_from_vacc        0
age_group                          0
education                          0
race                               0
sex                                0
income_poverty                     0
m

In [46]:
from sklearn.impute import KNNImputer

In [47]:
cols_with_missing = ['health_insurance', 'employment_industry', 'employment_occupation']
uniform_imputer = KNNImputer(n_neighbors=5, weights='uniform')
training_df[cols_with_missing] = uniform_imputer.fit_transform(training_df[cols_with_missing])

In [48]:
training_df.isnull().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
income_poverty                 0
marital_status                 0
rent_or_own                    0
employment_status              0
hhs_geo_re

### Cleaning testing data set

In [49]:
testing_df.isnull().sum()

respondent_id                      0
xyz_concern                       85
xyz_knowledge                    122
behavioral_antiviral_meds         79
behavioral_avoidance             213
behavioral_face_mask              19
behavioral_wash_hands             40
behavioral_large_gatherings       72
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            932
child_under_6_months             813
health_worker                    789
health_insurance               12228
opinion_xyz_vacc_effective       398
opinion_xyz_risk                 380
opinion_xyz_sick_from_vacc       375
opinion_seas_vacc_effective      452
opinion_seas_risk                499
opinion_seas_sick_from_vacc      521
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4497
m

In [50]:
testing_df['age_group'].unique()

array(['35 - 44 Years', '18 - 34 Years', '55 - 64 Years', '65+ Years',
       '45 - 54 Years'], dtype=object)

In [51]:
#taking max age as 85 years and replacing with average age
testing_df['age_group'].replace({'55 - 64 Years': 60, '35 - 44 Years': 40, '18 - 34 Years': 25, '65+ Years': 75,
       '45 - 54 Years': 50}, inplace=True)
testing_df['age_group'].unique()

array([40, 25, 60, 75, 50])

In [52]:
testing_df.dtypes

respondent_id                    int64
xyz_concern                    float64
xyz_knowledge                  float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_xyz                float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_xyz_vacc_effective     float64
opinion_xyz_risk               float64
opinion_xyz_sick_from_vacc     float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                        int64
education                       object
race                            object
sex                      

In [53]:
testing_df['education'].value_counts()

education
College Graduate    10186
Some College         7080
12 Years             5699
< 12 Years           2336
Name: count, dtype: int64

In [54]:
testing_df.fillna({'education': 'College Graduate'}, inplace = True)

In [55]:
testing_df['education'].unique()

array(['College Graduate', '12 Years', 'Some College', '< 12 Years'],
      dtype=object)

In [56]:
testing_df['education'] = testing_df['education'].astype('category')
testing_df['education'] = testing_df['education'].cat.codes
testing_df['education'].unique()

array([2, 0, 3, 1], dtype=int8)

In [57]:
testing_df['race'].value_counts()

race
White                21301
Black                 2174
Hispanic              1703
Other or Multiple     1530
Name: count, dtype: int64

In [58]:
testing_df['race'] = testing_df['race'].astype('category')
testing_df['race'] = testing_df['race'].cat.codes
testing_df['race'].unique()

array([1, 3, 0, 2], dtype=int8)

In [59]:
testing_df['sex'].value_counts()

sex
Female    15834
Male      10874
Name: count, dtype: int64

In [60]:
#replacing male and female with 1,0
testing_df['sex'].replace({'Male': 1, 'Female': 0}, inplace=True)
testing_df['sex'].unique()

array([0, 1])

In [61]:
testing_df['income_poverty'].value_counts()

income_poverty
<= $75,000, Above Poverty    12775
> $75,000                     6863
Below Poverty                 2573
Name: count, dtype: int64

In [62]:
testing_df.fillna({'income_poverty': '<= $75,000, Above Poverty'}, inplace = True)

In [63]:
testing_df['income_poverty'] = testing_df['income_poverty'].astype('category')
testing_df['income_poverty'] = testing_df['income_poverty'].cat.codes
testing_df['income_poverty'].unique()

array([1, 2, 0], dtype=int8)

In [64]:
testing_df['marital_status'].value_counts()

marital_status
Married        13548
Not Married    11718
Name: count, dtype: int64

In [65]:
testing_df.fillna({'marital_status': 'Married'}, inplace = True)

In [66]:
#replacing Marreid and Not Married with 1,0
testing_df['marital_status'].replace({'Married': 1, 'Not Married': 0}, inplace=True)
testing_df['marital_status'].value_counts()

marital_status
1    14990
0    11718
Name: count, dtype: int64

In [67]:
testing_df['rent_or_own'].value_counts()

rent_or_own
Own     18721
Rent     5951
Name: count, dtype: int64

In [68]:
testing_df.fillna({'rent_or_own': 'Own'}, inplace = True)

In [69]:
#replacing Own and Rent with 1,0
testing_df['rent_or_own'].replace({'Own': 1, 'Rent': 0}, inplace=True)
testing_df['rent_or_own'].unique()

array([0, 1])

In [70]:
testing_df['employment_status'].value_counts()

employment_status
Employed              13632
Not in Labor Force    10092
Unemployed             1513
Name: count, dtype: int64

In [71]:
testing_df.fillna({'employment_status': 'Employed'}, inplace = True)

In [72]:
#replacing Employed with 1 , Not in labor Force and Unemployed with 0
testing_df['employment_status'].replace({'Employed': 1, 'Not in Labor Force' :0 ,'Unemployed': 0}, inplace=True)
testing_df['employment_status'].unique()

array([1, 0])

In [73]:
testing_df['hhs_geo_region'].value_counts()

hhs_geo_region
lzgpxyit    4363
fpwskwrf    3241
qufhixun    3064
oxchjgsf    2987
bhuqouqj    2867
kbazzjca    2844
mlyzmhmf    2183
lrircsnp    2022
atmpeygn    1986
dqpwygqj    1151
Name: count, dtype: int64

In [74]:
testing_df['hhs_geo_region'] = testing_df['hhs_geo_region'].astype('category')
testing_df['hhs_geo_region'] = testing_df['hhs_geo_region'].cat.codes
testing_df['hhs_geo_region'].unique()

array([7, 1, 5, 6, 3, 8, 2, 9, 4, 0], dtype=int8)

In [75]:
testing_df['census_msa'].value_counts()

census_msa
MSA, Not Principle  City    11926
MSA, Principle City          7805
Non-MSA                      6977
Name: count, dtype: int64

In [76]:
testing_df['census_msa'] = testing_df['census_msa'].astype('category')
testing_df['census_msa'] = testing_df['census_msa'].cat.codes
testing_df['census_msa'].unique()

array([0, 2, 1], dtype=int8)

In [77]:
testing_df['employment_industry'].value_counts()

employment_industry
fcxhlnwr    2484
wxleyezf    1805
ldnlellj    1224
pxcmvdjn    1078
arjwrbjb     885
xicduogh     847
atmlpfrs     822
mfikgejo     649
vjjrobsf     567
rucpziij     538
xqicxuve     527
saaquncn     338
cfqqtusy     304
nduyfdeo     292
mcubkhph     262
dotnnunm     220
wlfvacwt     212
haxffmxo     160
msuufmds     132
phxvnwax      81
qnlwzans       6
Name: count, dtype: int64

In [78]:
testing_df['employment_industry'] = testing_df['employment_industry'].astype('category')
testing_df['employment_industry'] = testing_df['employment_industry'].cat.codes
testing_df['employment_industry'].unique()

array([ 1, 10, -1,  4, 12,  0,  8, 14, 18,  5,  6, 16,  2, 19,  3, 20, 17,
       15,  9,  7, 11, 13], dtype=int8)

In [79]:
testing_df['employment_industry'].replace(-1,np.nan, inplace = True)
testing_df['employment_industry'].unique()

array([ 1., 10., nan,  4., 12.,  0.,  8., 14., 18.,  5.,  6., 16.,  2.,
       19.,  3., 20., 17., 15.,  9.,  7., 11., 13.])

In [80]:
testing_df['employment_occupation'].value_counts()

employment_occupation
xtkaffoo    1748
mxkfnird    1561
emcorrxb    1284
cmhcxjea    1224
xgwztkwe    1138
hfxkjkmi     725
uqqtjvyb     501
qxajmpny     499
xqwwgdyp     475
kldqjyjy     446
tfqavkke     402
ccgxvspp     368
oijqvulv     346
bxpfxfdn     331
ukymxvdu     329
vlluhbov     325
haliazsg     300
rcertsgn     297
hodpvpew     253
dlvbwzss     245
xzmlyyjv     216
dcjcmpih     161
pvmttkik     108
Name: count, dtype: int64

In [81]:
testing_df['employment_occupation'] = testing_df['employment_occupation'].astype('category')
testing_df['employment_occupation'] = testing_df['employment_occupation'].cat.codes
testing_df['employment_occupation'].unique()

array([ 7, 20, 12, -1, 10,  2, 19, 15, 18,  3, 21,  8, 11,  9,  5, 13,  6,
       16,  4, 17,  1, 14,  0, 22], dtype=int8)

In [82]:
testing_df['employment_occupation'].replace(-1,np.nan, inplace = True)
testing_df['employment_occupation'].unique()

array([ 7., 20., 12., nan, 10.,  2., 19., 15., 18.,  3., 21.,  8., 11.,
        9.,  5., 13.,  6., 16.,  4., 17.,  1., 14.,  0., 22.])

In [83]:
testing_df.dtypes

respondent_id                    int64
xyz_concern                    float64
xyz_knowledge                  float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_xyz                float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_xyz_vacc_effective     float64
opinion_xyz_risk               float64
opinion_xyz_sick_from_vacc     float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                        int64
education                         int8
race                              int8
sex                      

In [84]:
testing_df.isnull().sum()

respondent_id                      0
xyz_concern                       85
xyz_knowledge                    122
behavioral_antiviral_meds         79
behavioral_avoidance             213
behavioral_face_mask              19
behavioral_wash_hands             40
behavioral_large_gatherings       72
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_xyz                 2160
doctor_recc_seasonal            2160
chronic_med_condition            932
child_under_6_months             813
health_worker                    789
health_insurance               12228
opinion_xyz_vacc_effective       398
opinion_xyz_risk                 380
opinion_xyz_sick_from_vacc       375
opinion_seas_vacc_effective      452
opinion_seas_risk                499
opinion_seas_sick_from_vacc      521
age_group                          0
education                          0
race                               0
sex                                0
income_poverty                     0
m

In [85]:
replace_mean_columns = ['xyz_concern','xyz_knowledge','behavioral_antiviral_meds','behavioral_avoidance','behavioral_face_mask','behavioral_wash_hands',
                        'behavioral_large_gatherings','behavioral_outside_home','behavioral_touch_face','doctor_recc_xyz',
                        'doctor_recc_seasonal','chronic_med_condition','child_under_6_months','health_worker','opinion_xyz_vacc_effective',
                        'opinion_xyz_risk','opinion_xyz_sick_from_vacc','opinion_seas_vacc_effective','opinion_seas_risk',
                        'opinion_seas_sick_from_vacc','household_adults','household_children']


for col in testing_df.columns:
    if col in replace_mean_columns:
        testing_df[col].fillna(testing_df[col].mean(), inplace=True)

testing_df.isnull().sum()

respondent_id                      0
xyz_concern                        0
xyz_knowledge                      0
behavioral_antiviral_meds          0
behavioral_avoidance               0
behavioral_face_mask               0
behavioral_wash_hands              0
behavioral_large_gatherings        0
behavioral_outside_home            0
behavioral_touch_face              0
doctor_recc_xyz                    0
doctor_recc_seasonal               0
chronic_med_condition              0
child_under_6_months               0
health_worker                      0
health_insurance               12228
opinion_xyz_vacc_effective         0
opinion_xyz_risk                   0
opinion_xyz_sick_from_vacc         0
opinion_seas_vacc_effective        0
opinion_seas_risk                  0
opinion_seas_sick_from_vacc        0
age_group                          0
education                          0
race                               0
sex                                0
income_poverty                     0
m

In [86]:
cols_with_missing = ['health_insurance', 'employment_industry', 'employment_occupation']
uniform_imputer = KNNImputer(n_neighbors=5, weights='uniform')
testing_df[cols_with_missing] = uniform_imputer.fit_transform(testing_df[cols_with_missing])

In [87]:
testing_df.isnull().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
income_poverty                 0
marital_status                 0
rent_or_own                    0
employment_status              0
hhs_geo_re

### SVM

In [88]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [89]:
y_xyz = training_labels['xyz_vaccine']
y_seasonal = training_labels['seasonal_vaccine']

svm_model_xyz = SVC(kernel='linear', probability=True)
svm_model_xyz.fit(training_df, y_xyz)

svm_model_seasonal = SVC(kernel='linear', probability=True)
svm_model_seasonal.fit(training_df, y_seasonal)

SVC(kernel='linear', probability=True)

In [90]:
# y_pred_xyz = svm_model_xyz.predict(testing_df)
y_proba_xyz = svm_model_xyz.predict_proba(testing_df)

# y_pred_seasonal = svm_model_seasonal.predict(testing_df)
y_proba_seasonal = svm_model_seasonal.predict_proba(testing_df)

In [91]:
print("\nPredicted Probabilities:")
print(y_proba_xyz[:5])
print("\nPredicted Probabilities:")
print(y_proba_seasonal[:5])


Predicted Probabilities:
[[0.94827658 0.05172342]
 [0.98405816 0.01594184]
 [0.88608234 0.11391766]
 [0.86337354 0.13662646]
 [0.93314695 0.06685305]]

Predicted Probabilities:
[[0.73575799 0.26424201]
 [0.97008816 0.02991184]
 [0.33625785 0.66374215]
 [0.10886942 0.89113058]
 [0.5653339  0.4346661 ]]


In [93]:
df_xyz = pd.DataFrame(y_proba_xyz, columns=['xyz_no', 'xyz_yes'])
df_seasonal = pd.DataFrame(y_proba_seasonal, columns=['seasonal_no', 'seasonal_yes'])

df_xyz_vaccine = df_xyz[['xyz_yes']].rename(columns={'xyz_yes': 'xyz_vaccine'})
df_seasonal_vaccine = df_seasonal[['seasonal_yes']].rename(columns={'seasonal_yes': 'seasonal_vaccine'})

respondent_ids = testing_df['respondent_id']

df_respondent_ids = pd.DataFrame(respondent_ids, columns=['respondent_id'])

result_df = pd.concat([df_respondent_ids, df_xyz_vaccine, df_seasonal_vaccine], axis=1)

result_df.to_csv('vaccine_probabilities.csv', index=False)

print("CSV file 'vaccine_probabilities.csv' created successfully.")


CSV file 'vaccine_probabilities.csv' created successfully.
